### ISSUE TITLE
scrub dist.ini from released distribution

### ISSUE THREAD

**Issue by yanick** [yanick/Template-Mustache#41]

**Comment by Grinnz** [comment]
What's the reason for this, out of curiosity? Leaving dist.ini out of the published distribution only makes it more difficult to explore packaging-related issues.

**Comment by yanick** [comment]
I mildly disagree. Publishing the dist.ini with the generated distribution is a little bit like publishing the Makefile alongside the compiled binary (same reasoning for not pushing the .gitignore or the MANIFEST.SKIP, really). 

If someone is a end-user, they will not really care about it. if they do want to dive into things and they are at a level where they can chew on a dist.ini, it's much more likely they'll clone the git repo rather than hack on a copy of distribution..

**Comment by Grinnz** [comment]
It's a bit like the .gitignore and MANIFEST.SKIP (when significant), yes -- without those you can't reconstruct the developer's exact release environment, if the connection to the source repository is lost. However the contents of .gitignore and MANIFEST.SKIP are rarely interesting, whereas the contents of dist.ini can dictate the entire development and release process. Additionally, metacpan exposes a link to dist.ini on release pages when present, and for example grep.cpan.me is sometimes used to grep through Dist::Zilla configurations across cpan; this is much more difficult to do in relation to linked git repos, if they are even in metadata. Put another way, the contents of dist.ini can be relevant to CPAN itself, as Dist::Zilla is a CPAN-based ecosystem/toolchain.

**Comment by Grinnz** [comment]
I don't really have a strong argument for why you should include dist.ini in published distributions, just that I don't believe there's a strong reason not to, and it occasionally is practically helpful to include it.
