### ISSUE TITLE
Access array element by index

### ISSUE THREAD

**Issue by jerowe** [yanick/Template-Mustache#48]
Any chance we could get this implementation?

https://github.com/janl/mustache.js/issues/158 ?

```
my $array = [1,2,3,4]

my $template = {{ array.1 }}

#Rendering Magic!
```

Pretty please?

**Comment by jerowe** [comment]
Huh. I can't get dot notation to work in general.

```
package Decs;

use Moose;
has 'some_hash' => (
    is      => 'rw',
    isa     => 'HashRef',
    default => sub {
        return { 'k1' => 'v1', 'k2' => 'v2' };
    }
);

package Main;

use Template::Mustache;

my $self = Decs->new();

my $template = <<EOT;
{{some_hash.k1}}
EOT

print Template::Mustache->render( $template, $self ), "\n";
```

Returns 

```
HASH(0x185a810)
```

What am I missing?

**Comment by jerowe** [comment]
When I'm not using moose it works. ;-(

```
my $thing = {
  some_hash => { 'k1' => 'v1', 'k2' => 'v2' }
};
print Template::Mustache->render( $template, $thing ), "\n";
```

**Comment by yanick** [comment]
The context is not resolved properly when dealing with an object or an array. Expect a patch tonight or tomorrow.

**Comment by jerowe** [comment]
Awesome! Thanks! I even made it into the tests. ;-)

I'm adding this as an optional templating engine in a project I have going, but I wouldn't have been able to release that functionality without this.

**Comment by yanick** [comment]
On 2017-08-30 11:11 PM, Jillian Rowe wrote:
> Awesome! Thanks! I even made it into the tests.

Yup, you're now forever intermeshed into this project. ^.^

Next thing you know, you'll be drawn into making a Pull Request. And then, before you know it, you'll become a co-maintainer. Mark my words...

> I'm adding this as an optional templating engine in a project I have going, but I wouldn't have been able to release that functionality without this.

Awesome!
