### ISSUE TITLE
render_file() method that just renders the darn file

### ISSUE THREAD

**Issue by abh** [yanick/Template-Mustache#6]
So far we've been using Template::Mustache with separate code that looks up the template data from an external source.

I needed it now to just read some files from disk and were surprised by the crazy (IMO) scheme to prefix the template names with the current class name.  In just about any application I've ever worked on, templates have just been in one or more "simple" search paths -- not related to the module name -- and I've never seen an application where each "user of templates" would have its own template engine subclass.

I realize it makes sense to you; but it doesn't make any sense to me.  :-)  I considered briefly sending a patch, but this is so deeply ingrained in the current implementation that it's really for you to decide if it could be cleaned up to be simpler/more intuitive.  Until then I'll just use Text::Caml in this particular application

**Comment by yanick** [comment]
You'll be happy to hear that in the upcoming version of Template::Mustache, I've done away with the path munging. What you give to `template_path` is now what is being used, without further magic. :-)

**Comment by yanick** [comment]
Published!
