### ISSUE TITLE
Partial rendering overrides to SSI includes

### ISSUE THREAD

**Issue by xerocole** [yanick/Template-Mustache#61]
Hi @yanick ,

It maybe a neat trick to override some internals of your module to treat partials slightly differently than intended. 

The idea I was thinking was more of efficiency on a larger scale statically generated site if we could potentially have all partials , instead of being rendered and extrapolated into the mustache file, to be written as an include file (yes Apache SSI ).

One of the problems I have is that when you start looking at a site of over 100k pages, and then you want to change the header for some reason. As you can imagine the process of recreating all those files would take some time. 

I know that there is nothing stopping people from just having this code in the actual mustache file in essence doing the same thing, but since Mustache has the same idea with partials, it would be neat to be able to tweak the behaviour to output rendered include files with references to those files using the notation of choice instead of trying to generate the whole file in its completeness.

Would love your thoughts and more so the "how" I could go about doing this. The dream I have is to leverage this for a mustache content generation engine would generate static sites.

Xerocole

**Comment by yanick** [comment]
I'm probably missing some details, but at first thought, this should be easy.

From what I understand, what you want is to have mustache render the intermediate files, that will be rendered by SSI before being punted out.

So the template would look like:

```
<body>
    <header>
     <!--#include virtual="/general/header.html" -->
    </header>
    <h1>Hi {{name}}!</h1>
</body>
```
(the header can be defined in a partial, the point being that we just print out the SSI directive)

And then the Mustache rendering turns it into

```
<body>
    <header>
     <!--#include virtual="/general/header.html" -->
    </header>
    <h1>Hi Bob!</h1>
</body>
```

When Apache gets its hands in that one, it'll populate the header and... you have hopefully the best of both worlds.


That sounds too easy. What am I missing? :-)

**Comment by xerocole** [comment]
@yanick yeah that is close but actually a bit more intergrated in terms of mustache. Let me see if I can tweak your example.

```
<body>
    <header>
     {{> /general/header }}
    </header>
    <h1>{{name}}!</h1>
</body>
```
Which after it was rendered it would look like this.

```
<body>
    <header>
     <!--#include virtual="/general/header.html" -->
    </header>
    <h1>Hi Bob!</h1>
</body>
```
And yes the partial would be parsed as well from mustache to html (in this example).

Make more sense?

**Comment by yanick** [comment]
Lemme see if I can tweak your tweak:

```
use Template::Mustache;

my $mustache = Template::Mustache->new(
    template => <<"END",
<body>
    <header>
     {{> /general/header }}
    </header>
    <h1>{{name}}!</h1>
</body>
END
    partials => sub {
        "<!--#include virtual='$_[0].html' -->\n"
    }
);

print $mustache->render({ name => 'Bob' });

```

**Comment by xerocole** [comment]
@yanick ... ok now how elegant is that. Very nice, so my last question on this is HOW is the CODEREF being executed? Is this a complete override of the partials subroutine? or will it try to parse the partial (inside contents first) and then execute the CODEREF after the parse (I think it is the override but want to check).

So if I wanted to add a small check to see if the file existed first and if not then treat it like a partial and write it out to the specified location then in the calling mustache file write the include statement how would that look like?

```
use Template::Mustache;

my $mustache = Template::Mustache->new(
    template => <<"END",
<body>
    <header>
     {{> /general/header }}
    </header>
    <h1>{{name}}!</h1>
</body>
END
    partials => sub {
        if (! -e "$_[0].html")
        { 
            ... render contents of partial (treat as mustache normally would) and write to $_[0].html
         }

       return "<!--#include virtual='$_[0].html' -->\n"
    }
);

print $mustache->render({ name => 'Bob' });

```

Thoughts?

**Comment by yanick** [comment]
Yup, it's a complete override. 

> So if I wanted to add a small check to see if the file existed first and if not then treat it like a partial and write it out to the specified location then in the calling mustache file write the include statement how would that look like?

Hmmm... Could be something like:

```
use Template::Mustache;
use Path::Tiny;

my %partials = (
  foo => sub { ... },
  bar => sub { ... },
);

my $mustache = Template::Mustache->new(
    template => <<"END",
<body>
    <header>
     {{> /general/header }}
    </header>
    <h1>{{name}}!</h1>
</body>
END
    partials => sub {
        if (! -e "$_[0].html")
        { 
             path( "$_[0].html )->spew( $partials{$_[0]}->() );
         }

       return "<!--#include virtual='$_[0].html' -->\n"
    }
);

print $mustache->render({ name => 'Bob' });
```

**Comment by xerocole** [comment]
@yanick thanks I believe that did the trick. Happy holidays and thank you again
