### ISSUE TITLE
Leading zeros truncated

### ISSUE THREAD

**Issue by AnotherOneAckap** [yanick/Template-Mustache#63]
Hello and thank you for you great work!
I met a problem when trying use numeric codes:

```
# perl -I local/lib/perl5/ -MTemplate::Mustache -E 'say Template::Mustache->render("{{.}}", " 098472")'
98472
```
I.e. string converts to number, and number then loses leading zeros.
Workaround here is to add some not-a-digit first, like invisible space, but i don't like it.

Is there some better way to fix it?

**Comment by yanick** [comment]
Hi!

Thanks for the kind words. :-)

And it seems that what you're hitting is less of a bug, and more following the specs. If a value looks like a number, the parser is intended to turn it into its canonical representation. See https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L92 and around it.

This being said, I'm thinking I should be able to add a flag to turn off this behavior. I'll see what I can do!

**Comment by yanick** [comment]
I think I have something for you in #64 

I'll try to merge and deploy sometime this week!

**Comment by yanick** [comment]
New version on its way to CPAN! Enjoy!
