### ISSUE TITLE
First example leads to warning

### ISSUE THREAD

**Issue by paulprocacci** [yanick/Template-Mustache#66]
length() used on @lineCount (did you mean "scalar(@lineCount)"?) at /usr/local/lib/perl5/site_perl/Template/Mustache.pm line 89.

print Template::Mustache->render(
    "Hello {{planet}}",
);

Summary of my perl5 (revision 5 version 32 subversion 1) configuration:

  Platform:
    osname=freebsd
    osvers=13.1-release-p6

If you need any additional information, let me know.

**Comment by yanick** [comment]
Which version of T::M are you using? The last time there was this line was in v0.5.1 in 2016. We're not at v1.4.0

**Comment by paulprocacci** [comment]
Ah, good ole package managers still have the old version.
That's my mistake and something I should have checked for.
Sorry for the noise.

**Comment by yanick** [comment]
No problem. Enjoy! :-)
